### ISSUE TITLE
 Free accounts 

### ISSUE THREAD

**Issue by 89z** [ejurgensen/librespot-c#1]
Currently this package only supports Spotify Premium accounts. This can be fixed by switching:

~~~
PRODUCT__PRODUCT_PARTNER
~~~

to:

~~~
PRODUCT__PRODUCT_CLIENT
~~~

and selecting normal or low audio qualities.

https://github.com/ejurgensen/librespot-c/blob/b4412f03a30adfce44624cd6d9731b38a70ffe92/src/connection.c#L903-L905

**Comment by ejurgensen** [comment]
Thanks a million for the suggestion, and also for looking at the implementation.

As you can see, I copied librespot, and they use PRODUCT_PARTNER. I'm nervous about unintended consequences from straying away from that. I guess you must be well into this subject, so perhaps you can add details about how you know that PRODUCT_CLIENT can be used? Do you know of other implementations using it?
