### ISSUE TITLE
make doesn't find 3rd-party libraries

### ISSUE THREAD

**Issue by hillstub** [ejurgensen/librespot-c#2]
Hi ejurgensen!
Thanks for making this library!
I'm trying to get this installed on my M1 mac, but unfortunately it fails with the following error:

```
In file included from src/librespot-c.c:53:
src/librespot-c-internal.h:13:10: fatal error: 'event2/event.h' file not found
#include <event2/event.h>
```

When I uncomment this line, it starts complaining about another library (gcrypt).

I did install all the dependencies using homebrew - am I doing something wrong?
Thanks in advance!

**Comment by ejurgensen** [comment]
Not sure why the headers aren't found on mac, but you will need to manually set the search path. Maybe something like:

```
export LD_LIBRARY_PATH=$(brew --prefix libevent)/lib
export CPATH=$(brew --prefix libevent)/include
```

**Comment by hillstub** [comment]
Thanks ejurgensen!

For my future self, these commands allowed me to build the library without errors:

```
export LD_LIBRARY_PATH="$(brew --prefix libevent)/lib:$(brew --prefix libgcrypt)/lib:$(brew --prefix libgpg-error)/lib:$(brew --prefix protobuf-c)/lib:$(brew --prefix json-c)/lib"

export CPATH="$(brew --prefix libevent)/include:$(brew --prefix libgcrypt)/include:$(brew --prefix libgpg-error)/include:$(brew --prefix protobuf-c)/include:$(brew --prefix json-c)/include"
```
