### ISSUE TITLE
Getting access token after logging in

### ISSUE THREAD

**Issue by hillstub** [ejurgensen/librespot-c#3]
Hi ejurgensen,
After logging in using username and password, what's the proper way to get the access token (with length of ~170 characters)?
Thanks in advance!

**Comment by ejurgensen** [comment]
The best way is to use the web API's Oauth to login and get an access token, and then use that for the library. You can't get an access token via the library.

You might be interested in examining [owntone](https://github.com/owntone/owntone-server) to see how to use.

**Comment by hillstub** [comment]
Thanks! The weird thing is that if I use the oauth workflow I get a type of access token that e.g. doesn't work with Spotify connect. I guess the difference is that oauth goes via a Spotify App, compared to direct authorization via this library (or librespot for that matter). When using librespot it gives an access token that does work with Spotify connect (but that library is written in rust, so i can't use it on an esp32).

**Comment by ejurgensen** [comment]
The access token must have the "stream" scope to work for playback. Note that my library isn't a Spotify Connect client like librespot is. It currently only supports playback (as a replacement for libspotify).

**Comment by hillstub** [comment]
Thanks for your comment! Adding "streaming" to the scope did the trick!! Thanks again!!
