### ISSUE TITLE
Calling the test program generates unvalid ogg file

### ISSUE THREAD

**Issue by l1mey112** [ejurgensen/librespot-c#4]
There isn't much documentation on `librespotc_open`, specifically what to pass as the "path".

After testing, the command below got me the farthest, reaching the end and generating the OGG. However the OGG is corrupt.

`./test1 'spotify:track:1gqQo4yfmQgho9ms8aEcw3' 'username' 'password'`

```
$ ffprobe testfile.ogg
[ogg @ 0x55e49200a700] Format ogg detected only with low score of 1, misdetection possible!
[ogg @ 0x55e49200a700] Codec not found
testfile.ogg: End of file
```

How could I remedy this?

**Comment by ejurgensen** [comment]
Yes, you are passing to the test client is correct. I also get an invalid ogg. Not sure why that is, needs further investigation.

FYI here is the implementation in OwnTone, maybe that is helpful for you: https://github.com/owntone/owntone-server/blob/master/src/inputs/spotify_librespotc.c
